"""""
home_assistant_summary.py
-------------------------

This helper script reads a daily environment log generated by
`home_assistant_logger.py` and produces a concise summary string. It
extracts the most recent log entry from the markdown file and formats
the values for use in email notifications or reports.

Usage:
  python home_assistant_summary.py /path/to/YYYY-MM-DD_environment_log.md

The script prints the summary to stdout. You can redirect the output
to a file or capture it in another program. The summary only includes
the last log entry in the file.
"""

import os
import re
import sys
from typing import Dict, List


def parse_latest_entry(lines: List[str]) -> Dict[str, str]:
    """Parse the last log entry from a list of lines.

    Args:
        lines: List of lines from the markdown log file.

    Returns:
        A mapping of metric names to their recorded values. If the file
        doesn't contain a recognizable log entry, returns an empty dict.
    """
    # Find the indices of log entries (lines starting with '## Log entry')
    indices = [i for i, line in enumerate(lines) if line.startswith("## Log entry")]
    if not indices:
        return {}
    # Get the start index of the last entry
    start_idx = indices[-1]
    # Collect lines until the next entry or end of file
    entry_lines = []
    for line in lines[start_idx + 1:]:
        if line.startswith("## Log entry"):
            break
        entry_lines.append(line.strip())
    # Parse bullet points of the form '- **Name**: value'
    data = {}
    pattern = re.compile(r"^- \*\*(.+?)\*\*: (.+)$")
    for line in entry_lines:
        match = pattern.match(line)
        if match:
            key = match.group(1)
            value = match.group(2)
            data[key] = value
    return data


def summarize_log(file_path: str) -> str:
    """Generate a summary string for the most recent log entry.

    Args:
        file_path: Path to the markdown log file.

    Returns:
        A human‑readable summary of the latest log entry. If no entry is
        found, returns an informative message.
    """
    if not os.path.isfile(file_path):
        return f"Log file not found: {file_path}"
    with open(file_path, encoding="utf-8") as f:
        lines = f.readlines()
    data = parse_latest_entry(lines)
    if not data:
        return "No log entries found in the file."
    summary_lines = ["최근 환경·수면·에어컨 데이터 요약:"]
    for key, value in data.items():
        summary_lines.append(f"- {key}: {value}")
    return "\n".join(summary_lines)


def main():
    if len(sys.argv) != 2:
        print("Usage: python home_assistant_summary.py /path/to/YYYY-MM-DD_environment_log.md")
        sys.exit(1)
    file_path = sys.argv[1]
    summary = summarize_log(file_path)
    print(summary)


if __name__ == "__main__":
    main()
""